import { useState } from "react";
import Head from "next/head";
import Container from "../components/Container";
import Navbar from "../components/Navbar";
import Filter from "../components/Filter";
import Card from "../components/Card";
import Link from "next/link";
import { getCountries } from "../lib/countries";

const defaultFilter = {
  country: "",
  continent: "",
};

export default function Home({ countries }) {
  const [filter, setFilter] = useState(defaultFilter);

  const handleFilterChange = (filterParam) => {
    setFilter(filterParam);
  };

  const filterCountries = () => {
    const filteredCountries = countries.filter((country) => {
      const isRightContinent =
        filter.continent === "" || filter.continent === country.region;

      return (
        country.name.toLowerCase().startsWith(filter.country.toLowerCase()) &&
        isRightContinent
      );
    });

    return filteredCountries;
  };

  return (
    <div>
      <Head>
        <title>Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container el="main">
        <Filter onChange={handleFilterChange} />
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-8">
          {filterCountries().map((country) => (
            <Link href={`/${country.cioc}`} key={country.cioc}>
              <a>
                <Card country={country} />
              </a>
            </Link>
          ))}
        </div>
      </Container>
    </div>
  );
}

export async function getStaticProps() {
  const countries = await getCountries();

  return {
    props: {
      countries,
    },
  };
}
